/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.vaydeal.member.req.mod;
import com.vaydeal.member.hash.Hashing;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Random;

/**
 * @company techvay
 * @author rifaie
 */
public class ForgotPassword {

    private final String mid;
    private final String email;
    private String membeType;
    private String password;
    private String name;
    private String passwordToken;

    public ForgotPassword(String uid, String email) {
        this.mid = uid;
        this.email = email;
    }

    public String getMembeType() {
        return membeType;
    }

    public void setMembeType(String membeType) {
        this.membeType = membeType;
    }

    public String getMid() {
        return mid;
    }

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword() {
        char[] chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/".toCharArray();
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < 44; i++) {
            char c = chars[random.nextInt(chars.length)];
            sb.append(c);
        }
        password = sb.toString();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPasswordToken() {
        return passwordToken;
    }

    public void setPasswordToken(String passwordToken) {
        this.passwordToken = passwordToken;
    }

    public void setAutogeneratedValues() throws Exception {
        setPassword();
        genHash();
    }

    /**
     *
     * @throws NoSuchAlgorithmException
     * @throws UnsupportedEncodingException
     * @throws java.security.spec.InvalidKeySpecException
     */
    public void genHash() throws NoSuchAlgorithmException, UnsupportedEncodingException, InvalidKeySpecException {
        passwordToken = Hashing.genVKey(email + password + System.currentTimeMillis());
    }
}
